# Generated by Django 2.0.6 on 2018-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATI',
            fields=[
                ('org_shortform_en', models.CharField(blank=True, max_length=32)),
                ('org_shortform_fr', models.CharField(blank=True, max_length=32)),
                ('organization_en', models.CharField(blank=True, max_length=150)),
                ('organization_fr', models.CharField(blank=True, max_length=150)),
                ('month_name_en', models.CharField(blank=True, max_length=32)),
                ('month_name_fr', models.CharField(blank=True, max_length=32)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('month', models.CharField(blank=True, help_text='Enter number 1 to 12', max_length=4)),
                ('request_summary_en', models.TextField(blank=True, null=True)),
                ('request_summary_fr', models.TextField(blank=True, null=True)),
                ('request_number', models.CharField(blank=True, max_length=150)),
                ('number_of_pages', models.CharField(blank=True, max_length=6)),
                ('disposition_en', models.CharField(blank=True, max_length=32)),
                ('disposition_fr', models.CharField(blank=True, max_length=32)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=32)),
                ('orgname_en', models.CharField(max_length=150)),
                ('orgname_fr', models.CharField(max_length=150)),
            ],
        ),
    ]
